apiVersion: v1
kind: Pod
metadata:
  name: pipetest-agent
  namespace: default
  labels:
    jenkins: slave
spec:
  serviceAccountName: jenkins
  containers:
    - name: python
      image: python:3.11-slim
      command:
        - cat
      tty: true
      volumeMounts:
        - name: jenkins-ca
          mountPath: /etc/ssl/certs/jenkins-ca
          readOnly: true
    - name: jnlp
      image: jenkins/inbound-agent:3355.v388858a_47b_33-2-jdk21
      args: ['$(JENKINS_SECRET)', '$(JENKINS_AGENT_NAME)']
      volumeMounts:
        - name: jenkins-ca
          mountPath: /etc/ssl/certs/jenkins-ca
          readOnly: true
  volumes:
    - name: jenkins-ca
      configMap:
        name: jenkins-ca-cert
